
name: Release

on:
    # Triggers the workflow on push events but only for the master branch
    push:
      tags:
        - "v*"
  
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
  

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --bin satori
      env:
        CARGO_TERM_COLOR: always
    - id: get_version
      uses: battila7/get-version-action@v2
    - name: Create release
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
            Compress-Archive -Path target\release\satori.exe -DestinationPath satori-${{ steps.get_version.outputs.version-without-v }}-${{ runner.os }}.zip
        else
            zip -jr satori-${{ steps.get_version.outputs.version-without-v }}-${{ runner.os }}.zip target/release/satori
        fi

        if [ "${{ runner.os }}" != "Windows" ]; then
            tar czf satori-${{ steps.get_version.outputs.version-without-v }}-${{ runner.os }}.tar.gz --directory=target/release satori
        fi
    - name: Upload artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./**/*.tar.gz
          ./**/*.zip

