
name: Release

on:
    # Triggers the workflow on push events but only for the master branch
    push:
      tags:
        - "v*"
  
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
  

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build for macOS
      run: cargo build --release --target x86_64-apple-darwin
      env:
        CARGO_TERM_COLOR: always
    - id: get_version
      uses: battila7/get-version-action@v2  
    - name: Create release linux
      run: |
        zip -r satori-${{ steps.get_version.outputs.version-without-v }}-x86_64-apple-darwin.zip target/x86_64-apple-darwin/satori
        tar czf satori-${{ steps.get_version.outputs.version-without-v }}-x86_64-apple-darwin.tar.gz target/x86_64-apple-darwin/satori
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: satori-cli
        path: |
          ./**/*.tar.gz
          ./**/*.zip
