
name: Release

on:
    # Triggers the workflow on push events but only for the master branch
    push:
      tags:
        - "v*"
  
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
  

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: cargo build --release
      env:
        CARGO_TERM_COLOR: always

    - name: Create release linux
      run: |
        zip -r satori.zip target/release/satori
        tar czf satori.tar.gz target/release/satori
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - id: get_version
      uses: battila7/get-version-action@v2    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my_project
        path: |
          satori-${{ steps.get_version.outputs.version-without-v }}-${{ runner.os }}-$(uname -m).zip
          satori-${{ steps.get_version.outputs.version-without-v }}-${{ runner.os }}-$(uname -m).tar.gz
