name: Rust

on:
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: satori_linux
        path: ./target/debug/satori
  
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: satori.exe
        path: ./target/debug/satori.exe
  
  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose           
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: satori_mac
        path: ./target/debug/satori
  
  clippy:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose    
    - name: clippy
      run: cargo clippy -- -D warnings

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit
        run: cargo audit
  
  fmt:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v4
    - name: fmt
      run: cargo fmt -- --check
      
